<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="turntable" params="parent *origin base_height plate_height plate_radius">
        <link name="turntable_base">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${base_height}" radius=".02" />
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${base_height}" radius=".02" />
                </geometry>
            </collision>
            
        <inertial>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <mass value="1" />
                <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
            </inertial>

        </link>
        <link name="turntable_plate">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${plate_height}" radius="${plate_radius}" />
                </geometry>
                <material name="DarkGray">
                    <color rgba="0.1 0.1 0.1 1.0" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <cylinder length="${plate_height}" radius="${plate_radius}" />
                </geometry>
            </collision>
            
        <inertial>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <mass value="1" />
                <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
            </inertial>

        </link>
        <joint name="turntable_joint" type="fixed">
            <!-- <parent link="${parent}"/> -->
            <parent link="${parent}"/>
            <child link="turntable_base" />
            <!-- <xacro:insert_block name="origin"/> -->
            <origin rpy="0 0 0" xyz="0 0 0${base_height/2}" />
        </joint>
        <joint name="turntable_revolve_joint" type="continuous">
            <parent link="turntable_base" />
            <child link="turntable_plate" />
            <origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 ${base_height/2}" />
            <!-- <limit effort="1000.0" lower="-6.28" upper="6.28" velocity="0.5"/> -->
            <limit effort="1000.0" velocity="0.5" /> 
            <axis xyz="0 0 1" />
        </joint>

        <transmission name="trans_turntable_revolve_joint">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="turntable_revolve_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="turntable_revolve_joint_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
</robot>