controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_turntable_controller
    type: $(arg fake_execution_type)
    joints:
      - turntable_revolve_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: turntable
    pose: home