<?xml version="1.0" ?>
<robot name="metrology" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find denso_robot_descriptions)/metrology_description/urdf/metrology.transmission.xacro"/>

	
	<link name="world"/>
	<link name="table_link">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				 <cylinder length="0.1" radius="0.1"/>
			</geometry>
			<material name="Pearl">
                    <color rgba="0.78 0.61 0.89 0.5" />
            </material>
		</visual>
		<!-- <collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				 <cylinder length="0.1" radius="0.1"/>
			</geometry>
		</collision> -->
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>

	<joint name="joint_w" type="fixed">
		<parent link="world"/>
		<child link="table_link"/>
		<origin xyz="0 0 0"/>
	</joint>


	<link name="proxy_link">
		<visual>
		<!-- change y here to length /2 -->
			<origin rpy="0 1.570796 1.570796" xyz="0 ${turntable_offset/2} 0"/>
			<geometry>
			<!-- change length here -->
				 <cylinder length="${turntable_offset}" radius="0.05"/>
			</geometry>
			<material name="Pearl">
                    <color rgba="0.78 0.61 0.89 0.5" />
            </material>
		</visual>
		<!-- <collision>
			<origin rpy="0 1.570796 1.570796" xyz="0 0.3 0"/>
			<geometry>
				<cylinder length="0.6" radius="0.05"/>
			</geometry>
		</collision> -->
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 1.570796 1.570796" xyz="0.000000 0.3 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>

	<link name="base_link">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/base_link.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/base_link.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>
	<link name="J1">
		<visual>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J1.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J1.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>
	<link name="J2">
		<visual>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J2.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J2.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>
	<link name="J3">
		<visual>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J3.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J3.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>
	<link name="J4">
		<visual>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J4.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J4.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>
	<link name="J5">
		<visual>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J5.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J5.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>
	<link name="J6">
		<visual>
			<origin rpy="0 0 0" xyz="0 0.0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J6.dae" scale="1 1 1"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://denso_robot_descriptions/metrology_description/meshes/J6.dae" scale="1 1 1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
		</inertial>
	</link>

	<gazebo reference="proxy_link">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="base_link">
		<material>Gazebo/CoM</material>
	</gazebo>
	<gazebo reference="J1">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="J2">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="J3">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="J4">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="J5">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="J6">
		<material>Gazebo/Gray</material>
	</gazebo>
	<gazebo reference="EEF_tool_mount">
		<material>Gazebo/CoM</material>
	</gazebo>

	<gazebo>
		<gravity>False</gravity>
	</gazebo>

	<joint name="joint_0" type="revolute">
		<parent link="table_link"/>
		<child link="proxy_link"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.000000"/>
		<axis xyz="-0.000000 -0.000000 1.000000"/>
		<limit effort="100" lower="-6.283185" upper="6.283185" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="joint_fixed" type="fixed">
		<parent link="proxy_link"/>
		<child link="base_link"/>
		<!-- Here change length -->
		<origin xyz="0 ${turntable_offset} 0"/> 
	</joint>

	<joint name="joint_1" type="revolute">
		<parent link="base_link"/>
		<child link="J1"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="0.00 0.00000 0.000000"/>
		<axis xyz="-0.000000 -0.000000 1.000000"/>
		<limit effort="100" lower="-2.96706" upper="2.96706" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="joint_2" type="revolute">
		<parent link="J1"/>
		<child link="J2"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="0.075000 0.000000 0.335000"/>
		<axis xyz="-0.000000 1.000000 -0.000000"/>
		<limit effort="100" lower="-1.745329" upper="2.356194" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="joint_3" type="revolute">
		<parent link="J2"/>
		<child link="J3"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.365000"/>
		<axis xyz="-0.000000 1.000000 -0.000000"/>
		<limit effort="100" lower="-2.076942" upper="2.949606" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="joint_4" type="revolute">
		<parent link="J3"/>
		<child link="J4"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="-0.090000 0.000000 -0.700000"/>
		<axis xyz="-0.000000 -0.000000 1.000000"/>
		<limit effort="100" lower="-3.316126" upper="3.316126" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="joint_5" type="revolute">
		<parent link="J4"/>
		<child link="J5"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 1.105000"/>
		<axis xyz="-0.000000 1.000000 -0.000000"/>
		<limit effort="100" lower="-2.094395" upper="2.094395" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="joint_6" type="revolute">
		<parent link="J5"/>
		<child link="J6"/>
		<origin rpy="0.000000 0.000000 0.000000" xyz="0.000000 0.000000 0.080000"/>
		<axis xyz="-0.000000 -0.000000 1.000000"/>
		<limit effort="100" lower="-6.283185" upper="6.283185" velocity="10"/>
		<dynamics damping="0" friction="0"/>
	</joint>


</robot>
